server:
  port: 9002

spring:
  application:
    name: nacos-payment-service

  # nacos地址
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 172.20.1.51:8888

# 监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"
