server:
  port: 3344

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tingyu1995/spring-cloud-config-test.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
