server:
  port: 3344

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tingyu1995/spring-cloud-config-test.git
  # rabbitmq配置
  rabbitmq:
    host: 172.20.2.52
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

# 监控点配置
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
