server:
  port: 7002

eureka:
  instance:
    hostname: eureka-server-7002
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 不需要检索服务
    fetch-registry: false
    # url
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/