server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tingyu

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.tingyu.cloud.entity



eureka:
  client:
    # 向注册中心注册
    register-with-eureka: true
    # 检索服务
    fetch-registry: true
    # 服务中心
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # eureka中显示的实例名称
    instance-id: payment8001
    # 显示ip地址
    prefer-ip-address: true
    # eureka client给server发送心跳的频率
    lease-renewal-interval-in-seconds: 1
    # eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，如果在这个时间内没收到下一次心跳，移除该client
    lease-expiration-duration-in-seconds: 2

