server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server-7001
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 不需要检索服务
    fetch-registry: false
    # url
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://localhost:7001/eureka/

  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 2000