server:
  port: 84

spring:
  application:
    name: nacos-order-service

  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # sentinel
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

# 监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启sentinel对openfeign支持
feign:
  sentinel:
    enabled: true