server:
  port: 2002

spring:
  application:
    name: seata-storage-service

  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: scf_tx_group

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_storage?useSSL=false
    username: root
    password: tingyu

mybatis:
  mapper-locations: classpath:mapper/*.xml