server:
  port: 83

spring:
  application:
    name: nacos-order-service

  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url: http://nacos-payment-service