server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    # 向注册中心注册
    register-with-eureka: true
    # 检索服务
    fetch-registry: true
    # 服务中心
    service-url:
      defaultZone: http://localhost:7001/eureka/